"""Dict <-> MySQL mapping that replaces the old app_state.json persistence.

The rest of the app keeps working with the legacy nested dict shape::

    {"products": {pid: {"platforms": {...}, "assets": {...}}}, "last_product_id": pid}

so all the existing merge logic (set_platform_state, _merge_platform_payloads,
update_product_state, file_manager prune) stays untouched -- only the load/save
boundary changes.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session, selectinload

from .db import session_scope
from .models import (
    AppMeta,
    PlatformAttribute,
    PlatformTag,
    Product,
    ProductAsset,
    ProductPlatform,
)

LAST_PRODUCT_ID_KEY = "last_product_id"

# Scalar keys promoted to real columns on product_platforms.
PROMOTED_COLUMNS = (
    "status",
    "title",
    "description",
    "caption",
    "affiliate_link",
    "product_url",
    "pin_id",
    "pin_url",
    "instagram_media_id",
    "generated_image_path",
    "generated_video_path",
    "video_url",
)
# List-valued platform fields stored as platform_tags rows.
TAG_KEYS = ("tags", "instagram_hashtags", "tiktok_hashtags", "youtube_keywords")
# Derived JSON-string mirrors of the list fields -- regenerated by _hydrate_preview.
PAYLOAD_KEYS = {f"{key}_payload" for key in TAG_KEYS}
# Large binary fields that must never be persisted (stripped by _sanitize_preview too).
BINARY_KEYS = {"image_data", "instagram_image_data"}
# Asset keys whose value is a list rather than a single path/url.
LIST_ASSET_KEYS = {"original_image_paths", "source_image_urls", "amazon_image_urls"}


# --------------------------------------------------------------------------- #
# Platform dict  ->  ORM rows
# --------------------------------------------------------------------------- #
def _platform_dict_to_row(platform_name: str, data: Dict[str, Any]) -> ProductPlatform:
    row = ProductPlatform(platform=platform_name)
    for key, value in (data or {}).items():
        if key in BINARY_KEYS or key in PAYLOAD_KEYS:
            continue
        if key in TAG_KEYS:
            if isinstance(value, list):
                for position, item in enumerate(value):
                    item_text = str(item).strip()
                    if item_text:
                        row.tags.append(
                            PlatformTag(tag_type=key, value=item_text[:255], position=position)
                        )
            continue
        if key in PROMOTED_COLUMNS:
            setattr(row, key, None if value is None else str(value))
            continue
        # Long-tail scalar -> JSON-encoded so bools/ints/strings round-trip exactly.
        row.attributes.append(
            PlatformAttribute(attr_key=key[:191], attr_value=json.dumps(value))
        )
    return row


def _iter_platform_entries(platforms: Dict[str, Any]):
    """Yield (platform_name, data_dict) flattening the instagram group."""
    for name, value in (platforms or {}).items():
        if name == "instagram" and isinstance(value, dict):
            for surface, surface_data in value.items():
                if isinstance(surface_data, dict):
                    yield surface, surface_data
        elif isinstance(value, dict):
            yield name, value


def _assets_dict_to_rows(assets: Dict[str, Any]) -> List[ProductAsset]:
    rows: List[ProductAsset] = []
    for key, value in (assets or {}).items():
        if isinstance(value, list):
            for position, item in enumerate(value):
                item_text = str(item).strip()
                if item_text:
                    rows.append(ProductAsset(asset_key=key, value=item_text, position=position))
        elif value not in (None, ""):
            rows.append(ProductAsset(asset_key=key, value=str(value), position=0))
    return rows


def _extract_product_columns(platforms: Dict[str, Any]) -> Dict[str, Optional[str]]:
    """Best-effort denormalized market/sku for easy querying."""
    market = sku = None
    for _name, data in _iter_platform_entries(platforms):
        market = market or data.get("market")
        sku = sku or data.get("sku_or_url")
    return {
        "market": str(market) if market else None,
        "sku_or_url": str(sku) if sku else None,
    }


# --------------------------------------------------------------------------- #
# ORM rows  ->  platform dict
# --------------------------------------------------------------------------- #
def _row_to_platform_dict(row: ProductPlatform) -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    for column in PROMOTED_COLUMNS:
        value = getattr(row, column)
        if value is not None:
            data[column] = value
    for attr in row.attributes:
        try:
            data[attr.attr_key] = json.loads(attr.attr_value) if attr.attr_value is not None else None
        except (json.JSONDecodeError, TypeError):
            data[attr.attr_key] = attr.attr_value
    tag_buckets: Dict[str, List[tuple]] = {}
    for tag in row.tags:
        tag_buckets.setdefault(tag.tag_type, []).append((tag.position, tag.value))
    for tag_type, items in tag_buckets.items():
        data[tag_type] = [value for _pos, value in sorted(items, key=lambda pair: pair[0])]
    return data


def _product_to_entry(product: Product) -> Dict[str, Any]:
    platforms: Dict[str, Any] = {}
    for row in product.platforms:
        platform_dict = _row_to_platform_dict(row)
        if row.platform.startswith("instagram_"):
            platforms.setdefault("instagram", {})[row.platform] = platform_dict
        else:
            platforms[row.platform] = platform_dict

    asset_buckets: Dict[str, List[tuple]] = {}
    for asset in product.assets:
        asset_buckets.setdefault(asset.asset_key, []).append((asset.position, asset.value))
    assets: Dict[str, Any] = {}
    for key, items in asset_buckets.items():
        ordered = [value for _pos, value in sorted(items, key=lambda pair: pair[0])]
        assets[key] = ordered if key in LIST_ASSET_KEYS else ordered[0]

    return {"platforms": platforms, "assets": assets}


# --------------------------------------------------------------------------- #
# Internal write helper (caller supplies the session)
# --------------------------------------------------------------------------- #
def _write_product(session: Session, product_id: str, entry: Dict[str, Any]) -> None:
    """Replace a single product's rows from the given entry dict."""
    product = session.get(Product, product_id)
    if product is None:
        product = Product(id=product_id)
        session.add(product)
    else:
        # Full replace: drop children, rebuild from the (already-merged) entry.
        product.platforms.clear()
        product.assets.clear()
        session.flush()

    platforms = entry.get("platforms") or {}
    assets = entry.get("assets") or {}
    columns = _extract_product_columns(platforms)
    product.market = columns["market"]
    product.sku_or_url = columns["sku_or_url"]

    for platform_name, data in _iter_platform_entries(platforms):
        product.platforms.append(_platform_dict_to_row(platform_name, data))
    for asset_row in _assets_dict_to_rows(assets):
        product.assets.append(asset_row)


def _set_meta(session: Session, key: str, value: Optional[str]) -> None:
    meta = session.get(AppMeta, key)
    if meta is None:
        session.add(AppMeta(key=key, value=value))
    else:
        meta.value = value


def _query_products(session: Session):
    return session.query(Product).options(
        selectinload(Product.platforms).selectinload(ProductPlatform.attributes),
        selectinload(Product.platforms).selectinload(ProductPlatform.tags),
        selectinload(Product.assets),
    )


# --------------------------------------------------------------------------- #
# Public API (mirrors the old JSON helpers)
# --------------------------------------------------------------------------- #
def load_app_state() -> Dict[str, Any]:
    """Return the full state dict, equivalent to the old app_state.json contents."""
    with session_scope() as session:
        products = {p.id: _product_to_entry(p) for p in _query_products(session).all()}
        meta = session.get(AppMeta, LAST_PRODUCT_ID_KEY)
        last_product_id = meta.value if meta and meta.value else ""
    return {"products": products, "last_product_id": last_product_id}


def get_product_entry(product_id: str) -> Dict[str, Any]:
    """Return a single product entry ({} if unknown)."""
    if not product_id:
        return {}
    with session_scope() as session:
        product = (
            _query_products(session).filter(Product.id == product_id).one_or_none()
        )
        return _product_to_entry(product) if product is not None else {}


def save_product_entry(product_id: str, entry: Dict[str, Any]) -> None:
    """Upsert a single product and mark it as the most recent one."""
    if not product_id:
        return
    with session_scope() as session:
        _write_product(session, product_id, entry)
        _set_meta(session, LAST_PRODUCT_ID_KEY, product_id)


def set_last_product_id(product_id: str) -> None:
    """Update only the last_product_id meta without touching any product data."""
    if not product_id:
        return
    with session_scope() as session:
        _set_meta(session, LAST_PRODUCT_ID_KEY, product_id)


def save_app_state(state: Dict[str, Any]) -> None:
    """Full sync: upsert every product present, delete those absent, set meta."""
    products = (state or {}).get("products") or {}
    last_product_id = (state or {}).get("last_product_id") or ""
    with session_scope() as session:
        existing_ids = {pid for (pid,) in session.query(Product.id).all()}
        incoming_ids = set(products.keys())
        for stale_id in existing_ids - incoming_ids:
            stale = session.get(Product, stale_id)
            if stale is not None:
                session.delete(stale)
        for product_id, entry in products.items():
            _write_product(session, product_id, entry or {})
        _set_meta(session, LAST_PRODUCT_ID_KEY, last_product_id)
